## Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [2, 3], [5, 6]])
print(a)
b = np.random.randn(2, 4)
print(b)

[[1 2]
 [2 3]
 [5 6]]
[[-0.02186377 -1.46034068 -0.7986156  -0.30521405]
 [-0.97741849  0.01907047 -0.38196877 -0.02294172]]


In [4]:
def nn(X):
    X = np.array(X)
    W1 = np.random.randn(3, 3)
    W2 = np.random.randn(3, 2)
    b1 = np.random.randn(3)
    b2 = np.random.randn(2)
    return W2.T.dot(W1.T.dot(X) + b1) + b2

In [5]:
X = [1, 2, 3]
print(nn(X))

[4.33821073 9.88723952]


## TensorFlow2

In [2]:
import tensorflow as tf

In [3]:
a = tf.constant(1.0)
b = tf.constant(3.0)
c = a + b
print(c)
print(c.numpy())

tf.Tensor(4.0, shape=(), dtype=float32)
4.0


In [4]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [8]:
tensor_4_4 = tf.ones((4, 4))
print(tensor_4_4)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(4, 4), dtype=float32)


In [9]:
tensor_4_5_6 = tf.ones((4, 5, 6))
print(tensor_4_5_6)

tf.Tensor(
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]], shape=(4, 5, 6), dtype=float32)


In [21]:
a = tf.constant([[1.0, 2], [3, 4]])
b = tf.ones([2, 2])
print(a)
print(b)
print(a + b)
print(a * b)
print(a @ b)
a = tf.constant([[[1., 2], [3, 4]],
                [[5, 6], [7, 8]],
                [[9, 10], [11, 12]]])
print(a)
print(tf.nn.softmax(a))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3. 3.]
 [7. 7.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]], shape=(3, 2, 2), dtype=float32)
tf.Tensor(
[[[0.26894143 0.7310586 ]
  [0.26894143 0.7310586 ]]

 [[0.26894143 0.7310586 ]
  [0.26894143 0.7310586 ]]

 [[0.26894143 0.7310586 ]
  [0.26894143 0.7310586 ]]], shape=(3, 2, 2), dtype=float32)


In [23]:
tf.reshape(a, (3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)>

In [24]:
b = tf.Variable(a)
print(b)

<tf.Variable 'Variable:0' shape=(3, 2, 2) dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)>


In [25]:
print(b.numpy)

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(3, 2, 2) dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)>>


In [26]:
print(tf.reshape(b, [3, 4]))

tf.Tensor(
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]], shape=(3, 4), dtype=float32)


In [32]:
print(tf.reduce_max(b, axis=1))

tf.Tensor(
[[ 3.  4.]
 [ 7.  8.]
 [11. 12.]], shape=(3, 2), dtype=float32)


In [33]:
a = tf.Variable([1., 2.])

In [34]:
print(a)

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>


In [35]:
a.assign([2, 3])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [36]:
x = tf.constant(1.)
with tf.GradientTape() as t:
    t.watch(x)
    y = x * x + tf.exp(x)
    dy_dx = t.gradient(y, x)
print(dy_dx)

tf.Tensor(4.7182817, shape=(), dtype=float32)
