# 第六周

## Numpy

In [1]:
import numpy as np

In [4]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array(((1, 2, 3), (4, 5, 6)))
g = np.array([['a', 'b'], ['c', 'd']])
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)])
f = np.array([[1, 2, 3], [4, 5, 6]], dtype='complex')
print(c)
print(d)
print(g)
print(e)
print(f)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[['a' 'b']
 ['c' 'd']]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [6]:
a = np.arange(4)
b = np.arange(4, 8)
print(a)
print(b)
print(a * b)

[0 1 2 3]
[4 5 6 7]
[ 0  5 12 21]


In [7]:
A = np.zeros((2, 4))
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
A = np.empty((2, 4))
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
A = np.arange(9).reshape((3, 3))
B = np.ones((3, 3))
print(A)
print(B)
print(A * B)
print(np.dot(A, B))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [12]:
A += 1
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(A.ravel())

[1 2 3 4 5 6 7 8 9]


In [15]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [25]:
sigmoid = lambda x: 1 / (1 + np.exp(-x))
tanh = lambda x: np.sinh(x) / np.cosh(x)
relu = lambda x: np.maximum(x, 0)

In [20]:
print(sigmoid(10))
print(tanh(10))
print(relu(10))

0.9999546021312976
0.9999999958776928


In [26]:
print(sigmoid(np.arange(-10, 10)))
print(tanh(np.arange(-10, 10)))
print(relu(np.arange(-10, 10)))

[4.53978687e-05 1.23394576e-04 3.35350130e-04 9.11051194e-04
 2.47262316e-03 6.69285092e-03 1.79862100e-02 4.74258732e-02
 1.19202922e-01 2.68941421e-01 5.00000000e-01 7.31058579e-01
 8.80797078e-01 9.52574127e-01 9.82013790e-01 9.93307149e-01
 9.97527377e-01 9.99088949e-01 9.99664650e-01 9.99876605e-01]
[-1.         -0.99999997 -0.99999977 -0.99999834 -0.99998771 -0.9999092
 -0.9993293  -0.99505475 -0.96402758 -0.76159416  0.          0.76159416
  0.96402758  0.99505475  0.9993293   0.9999092   0.99998771  0.99999834
  0.99999977  0.99999997]
[0 0 0 0 0 0 0 0 0 0 0 1 2 3 4 5 6 7 8 9]


In [29]:
def ReLU_Unit(x, W):
    return relu(np.sum(x * W))

In [39]:
def Logistic_Unit(x, W, b = 0):
    return sigmoid(np.sum(np.array(x) * np.array(W)) + b)

In [35]:
x = [1, 0, 1]
W = np.array([-0.21, 0.3, 0.7])
print(ReLU_Unit(x, W))
print(Logistic_Unit(x, W))

0.49
0.6201064323430902


In [61]:
AND = lambda x, y: int(Logistic_Unit([x, y], [20, 20], -30) + 0.5)
OR = lambda x, y: int(Logistic_Unit([x, y], [20, 20], -10) + 0.5)
NOT = lambda x: int(Logistic_Unit([x], [-20], 10) + 0.5)
NAND = lambda x, y: int(Logistic_Unit([x, y], [-20, -20], 30) + 0.5)
XOR = lambda x, y: AND(OR(x, y), NAND(x, y))

In [62]:
print(OR(0, 0), NAND(0, 0))
print(XOR(0, 0), XOR(0, 1), XOR(1, 0), XOR(1, 1))

0 1
0 1 1 0


In [64]:
def softmax(x):
    a = np.array(x)
    b = np.exp(a)
    return b / np.sum(b)

In [68]:
logit = lambda x: np.log(x / (1 - x))

In [69]:
print(logit(0.9))

2.1972245773362196


In [65]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(softmax(x))

[2.12078996e-04 5.76490482e-04 1.56706360e-03 4.25972051e-03
 1.15791209e-02 3.14753138e-02 8.55587737e-02 2.32572860e-01
 6.32198578e-01]


In [73]:
import pandas as pd

In [77]:
CSV_FILE_PATH = './数据.csv'
df = pd.read_csv(CSV_FILE_PATH, encoding='GBK')
print(df)
    

   Q1_性别  Q2_身高（厘米）  Q3_体重 （公斤）  Q4_头发长度（厘米）
0      男        190          70            7
1      女        160          45           20
2      男        179          61            5
3      女        173          60           50
4      男        175          70           15
5      女        162          53           30
6      男        170          80            5
7      男        168          55            5
8      男        175          65            4
9      男        175          70            4
10     女        158          47           50
11     男        180          68            3
12     男        180          75            5
13     女        160          49           20
14     男        167          60           12
15     女        160          49           40
16     男        175          66           15
17     男        188          70           15
18     男        171          63           10
19     男        175          75           10
20     男        172          65            3
21     女  